services:
  - type: web
    name: smart-city-system
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn SmartCitySystem.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: true
      - key: DEBUG
        value: true
      - key: ALLOWED_HOSTS
        sync: true
      - key: DATABASE_URL
        fromDatabase:
          name: smart-city-db
          property: connectionString

databases:
  - name: smart-city-db
    databaseName: smartcity
    user: smartcity


